services:
  # Backend servis 1: Stakeholders
  stakeholders-service:
    build:
      context: ./services/stakeholders-service
    ports:
      - "8081:8080" # Pristup sa vašeg računara: localhost:8081
    networks:
      - app-network
    depends_on:
      - mysql-db

  # Backend servis 2: Blog
  blog-service:
    build:
      context: ./services/blog-service
    ports:
      - "8082:8080" # Pristup sa vašeg računara: localhost:8082
    networks:
      - app-network
    depends_on:
      - mysql-db

  # Frontend aplikacija
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80" # Pristup sa vašeg računara: localhost:3000
    networks:
      - app-network
    depends_on:
      - stakeholders-service
      - blog-service

  # MySQL Baza Podataka
  mysql-db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root_password"
      MYSQL_DATABASE: "turisticka_agencija_db"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
    ports:
      - "3307:3306" # Pristup bazi sa vašeg računara preko alata (npr. Workbench)
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

# Mreža koja omogućava komunikaciju između svih servisa
networks:
  app-network:
    driver: bridge

# Volumen za čuvanje podataka baze
volumes:
  mysql-data:
