services:
  # 1. Service Discovery
  eureka-server:
    build: ./eureka-server
    ports:
      - "8761:8761"
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  # 2. API Gateway
  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "8000:80" # Spoljašnji:Unutrašnji
    networks:
      - app-network
    environment:
      - Eureka__Client__ServiceUrl=http://eureka-server:8761/eureka
      # --- POČETAK FINALNE ISPRAVKE: Kažemo .NET-u da sluša na portu 80 ---
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      eureka-server:
        condition: service_healthy
      stakeholders-service:
        condition: service_healthy
      blog-service:
        condition: service_healthy

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"  # API port
      - "9001:9001"  # Port za web interfejs
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
      start_period: 10s
  # 3. Stakeholders Servis
  stakeholders-service:
    build:
      context: ./services/stakeholders-service
    environment:
      - PORT=8001
      - SERVICE_NAME=STAKEHOLDERS-SERVICE
      - EUREKA_URL=http://eureka-server:8761/eureka
      - DB_USER=user
      - DB_PASS=password
      - DB_HOST=stakeholders-db
      - DB_NAME=stakeholders_db
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8001/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    depends_on:
      stakeholders-db:
        condition: service_started
      eureka-server:
        condition: service_healthy
      minio:
        condition: service_healthy

  # 4. Blog Servis
  blog-service:
    build:
      context: ./services/blog-service
    environment:
      - PORT=8002
      - SERVICE_NAME=BLOG-SERVICE
      - EUREKA_URL=http://eureka-server:8761/eureka
      - DB_USER=user
      - DB_PASS=password
      - DB_HOST=blog-db
      - DB_NAME=blog_db
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8002/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    depends_on:
      blog-db:
        condition: service_started
      eureka-server:
        condition: service_healthy

  # 5. Frontend
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    networks:
      - app-network
    depends_on:
      - api-gateway

  # 6. Baze Podataka
  stakeholders-db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root_password"
      MYSQL_DATABASE: "stakeholders_db"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
    ports:
      - "3307:3306"
    volumes:
      - stakeholders-data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  blog-db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root_password"
      MYSQL_DATABASE: "blog_db"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
    ports:
      - "3308:3306"
    volumes:
      - blog-data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

networks:
  app-network:
    driver: bridge

volumes:
  stakeholders-data:
  blog-data:
  minio-data:
